### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by benjaminhr** [kailau02/Dolly-Zoom#1]
Love the project! Just a couple things that would be great to have:
- a `requirements.txt` which can be created via `pip3 freeze > requirements.txt` 
- a `.gitignore`
- setup/running instructions in `README.md`

**Comment by kailau02** [comment]
Sorry, I'm a noob when it comes to Github. I added the things you listed. If there is anything else that should be added to ``README.md`` just let me know. Thanks for the suggestions!

**Comment by benjaminhr** [comment]
I think you forgot to commit your `requirements.txt`

**Comment by kailau02** [comment]
Oops, you're right. I just added it.
