### ISSUE TITLE
ESC key to quit not working on macOS

### ISSUE THREAD

**Issue by benjaminhr** [kailau02/Dolly-Zoom#2]
When I hit my `ESC` key, the program does not quit - running on macOS btw.

Adding a print statement after `k = ...` just gave `255` every millisecond, hitting `ESC` didn't print a different keycode as if it wasn't registered.

**Comment by kailau02** [comment]
I changed the line to ``k = cv2.waitKey(30)`` and am no longer seeing any issues. Let me know if you still have this problem.
